name: PowerShell CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-pwsh@v2
        with:
          pwsh-version: "7.4.1"

      - name: Install PSScriptAnalyzer
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
        shell: pwsh

      - name: Lint scripts
        run: |
          Invoke-ScriptAnalyzer -Path ./src,./scripts -Recurse -Severity Warning
        shell: pwsh

      - name: Run Pester tests
        run: |
          Invoke-Pester -Path ./tests -EnableExit
        shell: pwsh
