name: PowerShell CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test PowerShell Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # pwsh is already installed on ubuntu-latest

      - name: Ensure PSScriptAnalyzer is available
        shell: pwsh
        run: |
          $module = Get-Module -ListAvailable PSScriptAnalyzer | Sort-Object Version -Descending | Select-Object -First 1
          if (-not $module) {
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
          } else {
            Import-Module $module.Name -MinimumVersion $module.Version -ErrorAction Stop
          }
          Get-Module PSScriptAnalyzer | Format-Table Name,Version

      - name: Lint scripts (repo root)
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./tests -EnableExit
