name: PowerShell CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Lint and Test PowerShell Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: egor-tensin/setup-powershell@v1
        with:
          version: '7.4.1'

      - name: Install PSScriptAnalyzer
        run: |
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser
        shell: pwsh

      - name: Lint scripts
        run: |
          Invoke-ScriptAnalyzer -Path ./src,./scripts -Recurse -Severity Warning
        shell: pwsh

      - name: Run Pester tests
        run: |
          Invoke-Pester -Path ./tests -EnableExit
        shell: pwsh
