name: PowerShell CI

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      # No setup action needed — pwsh is preinstalled

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Lint scripts
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src,./scripts -Recurse -Severity Warning

      - name: Run Pester tests
        shell: pwsh
        run: |
          Invoke-Pester -Path ./tests -EnableExit
